version: "3"
services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: workout
      POSTGRES_USER: workout
      POSTGRES_DB: workout
    ports:
      - "5432:5432"

  db_mongo:
    image: mongo:6
    ports:
      - "27017:27017"